[package]
name = "payment-engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1.0"
serde = { version = "1.0.136", features = ["derive"] }
csv = "1.1.6"
